<?php
/**
 * Created by Vitaly Iegorov <egorov@samsonos.com>
 * on 21.05.14 at 10:51
 */
namespace samsonos\php\skeleton;

/**
 * Class for interacting with SamsonPHP
 * @author Vitaly Egorov <egorov@samsonos.com>
 * @copyright 2014 SamsonOS
 * @version 1.0.0
 */
class Skeleton extends \samson\core\ExternalModule
{
    /** @var string Module identifier */
    public $id = 'skeleton';

    /**
     * Create recursevely directory if it does not exists
     * @param string $path path to directory
     */
    protected function createDir($path)
    {
        if (!file_exists($path)) {
            mkdir($path, 0775, true);
        }
    }

    /**
     * Controller for generating local module
     * @param string $name Local module name
     */
    public function __generate($name)
    {
        if( isset($name{0}) ) {

            // Create view folder for module
            $view = __SAMSON_VIEW_PATH.$name;
            $this->createDir($view);
            $view .= '/index.php';
            if(!file_exists($view)) {
                // Create view file
                file_put_contents($view,
'<!-- View['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').'-->

'
                );
            }

            // If controller not exists
            $controller = __SAMSON_CONTOROLLER_PATH;
            $this->createDir($controller);
            $controller .= $name.'.php';
            if(!file_exists($controller)) {
                // Create controller file
                file_put_contents($controller,
'<?php /** Controller['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').' */
function '.$name.'__HANDLER()
{
    // Your code here
    m()->view("'.$name.'/index")->title("'.$name.'");
}
'
                );
            }

            // Create less file
            $less = 'css';
            $this->createDir($less);
            $less .= '/'.$name.'.less';
            if(!file_exists($less)) {
                // Create less file
                file_put_contents($less,
'/* LESS['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').' */
#'.$name.'{

}'
                );
            }

            // Create less file
            $js = 'js';
            $this->createDir($js);
            $js .= '/'.$name.'.coffee';
            if(!file_exists($js)) {
                // Create coffee file
                file_put_contents($js,
'# COFFEE['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').'

'
                );
            }

            elapsed('Local module '.$name.' was successfully created');
        }

        $this->html(' ');
    }
}

