<?php
/**
 * Created by Vitaly Iegorov <egorov@samsonos.com>
 * on 21.05.14 at 10:51
 */
namespace samsonos\php\skeleton;

/**
 * Class for interacting with SamsonPHP
 * @author Vitaly Egorov <egorov@samsonos.com>
 * @copyright 2014 SamsonOS
 * @version 1.0.0
 */
class Skeleton extends \samson\core\ExternalModule
{
    /** @var string Module identifier */
    public $id = 'skeleton';

    /** Flag for creating coffee file or regular javascript */
    public $createCoffee = false;

    /** Flag for debugging less */
    public $lessDebug = false;

    /** Collection of tag names to ignore within less building */
    public $lessIgnore = array(
        'head',
        'meta',
        'script',
        'link',
        'title',
        'br'
    );

    /** Collection of created less selectors */
    protected $lessSelectors = array();

    /**
     * Create recursevely directory if it does not exists
     * @param string $path path to directory
     */
    protected function createDir($path)
    {
        if (!file_exists($path)) {
            mkdir($path, 0775, true);
        }
    }

    /** Less sandbox controller for testing     */
    public function __lesssandbox()
    {
        s()->template('view/dashboard.vphp');

        if(isset($_POST['source'])) {
            // Build LESS node tree
            $lessTree = new \samsonos\php\skeleton\Tree();

            // Prepare view
            $this->view('view/dashboard')
                ->source($_POST['source'])
                ->less($lessTree->toLESS($_POST['source']));

        } else {
            $this->view('view/dashboard');
        }
    }

    /**
     * Controller for building .less skeleton from html tree
     */
    public function __less()
    {
        s()->async(true);

        $less = '';

        $path = implode('/', url()->parameters);
        $name = implode('_', url()->parameters);

        // Find path to view
        $_path = m('local')->findView($path);

        $this->createDir('css');

        // Generate pass to less file
        $lessPath = 'css/'.$name.'.less';

        // If we have found view file
        if (file_exists($_path)) {

            // If we have not generated this file before
            if (!file_exists($lessPath)) {

                // Set ignored DOM nodes
                \samsonos\php\skeleton\Tree::$ignoredNodes = $this->lessIgnore;

                // Build LESS node tree
                $lessTree = new \samsonos\php\skeleton\Tree($_path);

                // Write generated file
                file_put_contents($lessPath, $lessTree->toLESS());

                elapsed('Creating LESS file: '.$lessPath);

            } else {
                e('LESS file alerady exists(##) - remove it', E_SAMSON_CORE_ERROR, $lessPath);
            }

        } else {
            e('View file not found(##)', E_SAMSON_CORE_ERROR, $path);
        }
    }

    /**
     * Controller for generating local module
     * @param string $name Local module name
     */
    public function __generate($name)
    {
        if( isset($name{0}) ) {

            // Create view folder for module
            $view = __SAMSON_VIEW_PATH.$name;
            $this->createDir($view);
            $view .= '/index.php';
            if(!file_exists($view)) {
                // Create view file
                file_put_contents($view,
'<!-- View['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').'-->

'
                );
            }

            // If controller not exists
            $controller = __SAMSON_CONTOROLLER_PATH;
            $this->createDir($controller);
            $controller .= $name.'.php';
            if(!file_exists($controller)) {
                // Create controller file
                file_put_contents($controller,
'<?php /** Controller['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').' */
function '.$name.'__HANDLER()
{
    // Your code here
    m()->view("'.$name.'/index")->title("'.$name.'");
}
'
                );
            }

            // Create less file
            $less = 'css';
            $this->createDir($less);
            $less .= '/'.$name.'.less';
            if(!file_exists($less)) {
                // Create less file
                file_put_contents($less,
'/* LESS['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').' */
#'.$name.'{

}'
                );
            }

            // Create less file
            $js = 'js';
            $this->createDir($js);
            $js .= '/'.$name.($this->createCoffee?'.coffee':'.js');
            if(!file_exists($js)) {
                // Create coffee file
                file_put_contents($js,
                    $this->createCoffee ?'# COFFEE['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i')
                    : '/* COFFEE['.$name.'] was automatically generated by SamsonPHP/Skeleton application on '.date('d.m.y H:i').'*/'
                );
            }

            elapsed('Local module '.$name.' was successfully created');
        }

        $this->html(' ');
    }
}

